services:
  whiteboard:
    build: .
    container_name: whiteboard
    privileged: true
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/app
    environment:
      PORT: "80"
      DB_PATH: /tmp/whiteboard.db
      DEBUG: "1"
